version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: blinx
      POSTGRES_PASSWORD: blinx_password
      POSTGRES_DB: blinx_signaturerx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blinx"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: